### ISSUE TITLE
Add GitHub issue and PR templates

### ISSUE THREAD

**Issue by YourAKShaw** [rohitg00/devops-twitter-bot#8]
Add detailed GitHub issue and PR templates for efficient contribution.

**Comment by akshaywakhare** [comment]
Hi! @Ak-Shaw can I work on this?

**Comment by YourAKShaw** [comment]
Assigned. 👍🏻

**Comment by akshaywakhare** [comment]
@Ak-Shaw are blank issues (ones created without using the template)  to be allowed?

**Comment by YourAKShaw** [comment]
Ideally no. Only maintainers should be allowed to do that. Also, it'll be great if you're able to add a generic template for needs where the use case isn't quite obvious.

**Comment by akshaywakhare** [comment]
Okay, will look into that.

**Comment by akshaywakhare** [comment]
Please review PR #13 for issue templates, working on PR templates next

**Comment by YourAKShaw** [comment]
@akshaywakhare great job with the issue templates! 👏🏻 

@rohitg00, in order to create a blank issue, go to [https://github.com/rohitg00/devops-twitter-bot/issues/new/](https://github.com/rohitg00/devops-twitter-bot/issues/new/).

@akshaywakhare can you kindly check whether this URL opens up for you or not? In the ideal case it shouldn't. Need to be sure.

That said, we're set with the initial requirements for the issue templates. Eagerly waiting for the PR templates. Thank you for contributing! 😺

**Comment by akshaywakhare** [comment]
@Ak-Shaw the above url is redirecting to https://github.com/rohitg00/devops-twitter-bot/issues/new/choose where I'm required to choose amongst the available templates.

**Comment by akshaywakhare** [comment]
Please review PR #15 for pr templates
